Models/Consumptie.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentTaste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumptie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumptie()
        {
            this.ConsumptieGroep = new HashSet<ConsumptieGroep>();
        }
    
        public string consumptieCode { get; set; }
        public string consumptieNaam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumptieGroep> ConsumptieGroep { get; set; }
    }
}

Controllers/ConsumptieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExcellentTaste.Models;

namespace ExcellentTaste.Controllers
{
    [Authorize]
    public class ConsumptieController : Controller
    {
        private Entities db = new Entities();

        // GET: Consumptie
        public ActionResult Index()
        {
            return View(db.Consumptie.ToList());
        }

        // GET: Consumptie/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consumptie consumptie = db.Consumptie.Find(id);
            if (consumptie == null)
            {
                return HttpNotFound();
            }
            return View(consumptie);
        }

        // GET: Consumptie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Consumptie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "consumptieCode,consumptieNaam")] Consumptie consumptie)
        {
            if (ModelState.IsValid)
            {
                db.Consumptie.Add(consumptie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(consumptie);
        }

        // GET: Consumptie/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consumptie consumptie = db.Consumptie.Find(id);
            if (consumptie == null)
            {
                return HttpNotFound();
            }
            return View(consumptie);
        }

        // POST: Consumptie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "consumptieCode,consumptieNaam")] Consumptie consumptie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(consumptie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(consumptie);
        }

        // GET: Consumptie/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consumptie consumptie = db.Consumptie.Find(id);
            if (consumptie == null)
            {
                return HttpNotFound();
            }
            return View(consumptie);
        }

        // POST: Consumptie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Consumptie consumptie = db.Consumptie.Find(id);
            db.Consumptie.Remove(consumptie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Consumptie/Create.cshtml
@model ExcellentTaste.Models.Consumptie

@{
    ViewBag.Title = "Toevoegen";
}

<h2>Toevoegen</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Consumptie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.consumptieCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.consumptieCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.consumptieCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.consumptieNaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.consumptieNaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.consumptieNaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Toevoegen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Consumptie/Delete.cshtml
@model ExcellentTaste.Models.Consumptie

@{
    ViewBag.Title = "Verwijder";
}

<h2>Verwijder</h2>

<h3>Weet u zeker dat u dit wilt verwijderen?</h3>
<div>
    <h4>Consumptie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.consumptieNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.consumptieNaam)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar overzicht", "Index")
        </div>
    }
</div>

Views/Consumptie/Details.cshtml
@model ExcellentTaste.Models.Consumptie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Consumptie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.consumptieNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.consumptieNaam)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Wijzig", "Edit", new { id = Model.consumptieCode }) |
    @Html.ActionLink("Terug naar overzicht", "Index")
</p>

Views/Consumptie/Edit.cshtml
@model ExcellentTaste.Models.Consumptie

@{
    ViewBag.Title = "Edit";
}

<h2>Wijzig</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Consumptie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.consumptieCode)

        <div class="form-group">
            @Html.LabelFor(model => model.consumptieNaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.consumptieNaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.consumptieNaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Consumptie/Index.cshtml
@model IEnumerable<ExcellentTaste.Models.Consumptie>

@{
    ViewBag.Title = "Index";
}

<h2>Overzicht consumptie hoofdgroepen</h2>

<p>
    @Html.ActionLink("Toevoegen", "Create", "Consumptie", null, new { @class = "btn btn-primary btn-large" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.consumptieNaam)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.consumptieNaam)
        </td>
        <td>
            @Html.ActionLink("Wijzig", "Edit", new { id=item.consumptieCode }) |
            @Html.ActionLink("Details", "Details", new { id=item.consumptieCode }) |
            @Html.ActionLink("Verwijder", "Delete", new { id=item.consumptieCode })
        </td>
    </tr>
}

</table>