Models/Reservering.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentTaste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservering()
        {
            this.Bestelling = new HashSet<Bestelling>();
        }
    
        public int reserveringId { get; set; }
        public int klantId { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan tijd { get; set; }
        public int tafel { get; set; }
        public int aantalPersonen { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime datumToegevoegd { get; set; }
        public Nullable<System.DateTime> bonDatum { get; set; }
        public string betalingswijze { get; set; }
        public Nullable<decimal> bonTotaal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelling> Bestelling { get; set; }
        public virtual Klant Klant { get; set; }
    }
}

Controllers/ReserveringController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExcellentTaste.Models;

namespace ExcellentTaste.Controllers
{
    [Authorize]
    /// <summary>
    /// Controller for reservations
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class ReserveringController : Controller
    {
        /// <summary>
        /// The database
        /// </summary>
        private Entities db = new Entities();

        // GET: Reservering
        /// <summary>
        /// Get a list of all reservations
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int klantId = 0)
        {
            List<Reservering> reservering;
            if (klantId > 0)
            {
                reservering = db.Reservering.Where(r=>r.klantId == klantId).Include(r => r.Klant).ToList();
            }
            else
            {
                reservering = db.Reservering.Include(r => r.Klant).ToList();
            }
            return View(reservering.OrderByDescending(r=>r.datum).ToList());
        }

        // GET: Reservering
        /// <summary>
        /// Get a list of todays reservations
        /// </summary>
        /// <returns></returns>
        public ActionResult Today()
        {
            var reservering = db.GET_TODAYS_RESERVATIONS();
            return View(reservering.ToList());
        }

        // GET: Reservering/Details/5
        /// <summary>
        /// Gets the details of a reservation
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservering reservering = db.Reservering.Find(id);
            if (reservering == null)
            {
                return HttpNotFound();
            }
            return View(reservering);
        }

        // GET: Reservering/Create
        /// <summary>
        /// Creates a new reservation.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create(int klantId = 0)
        {
            //ViewBag.klantId = new SelectList(db.Klant, "klantId", "klantNaam");
            VMReservering reservering = new VMReservering();
            if (klantId != 0)
                reservering.klantId = klantId;
            return View(reservering);
        }

        // POST: Reservering/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Creates the specified reservation.
        /// </summary>
        /// <param name="reservering">The reservation.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "klantId,datum,tijd,tafel,aantalPersonen")] VMReservering reservering)
        {
            if (ModelState.IsValid)
            {
                Reservering res = new Reservering();
                res.tafel = reservering.tafel;
                res.aantalPersonen = reservering.aantalPersonen;
                res.datum = reservering.datum;
                res.tijd = reservering.tijd;
                res.klantId = reservering.klantId;
                res.status = 1;
                res.datumToegevoegd = DateTime.Now;
                db.Reservering.Add(res);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.klantId = new SelectList(db.Klant, "klantId", "klantNaam", reservering.klantId);
            return View(reservering);
        }

        // GET: Reservering/Edit/5
        /// <summary>
        /// Edits the specified reservation.
        /// </summary>
        /// <param name="id">The id of the reservation.</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservering reservering = db.Reservering.Find(id);
            if (reservering == null)
            {
                return HttpNotFound();
            }
            ViewBag.klantId = new SelectList(db.Klant, "klantId", "klantNaam", reservering.klantId);
            return View(reservering);
        }

        // POST: Reservering/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Edits the specified reservation.
        /// </summary>
        /// <param name="reservering">The Get a list of all reservations.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "reserveringId,klantId,datum,tijd,tafel,aantalPersonen,status,datumToegevoegd,bonDatum,betalingswijze")] Reservering reservering)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservering).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.klantId = new SelectList(db.Klant, "klantId", "klantNaam", reservering.klantId);
            return View(reservering);
        }

        // GET: Reservering/Delete/5
        /// <summary>
        /// Deletes the specified reservation.
        /// </summary>
        /// <param name="id">The identifier of the reservation.</param>
        /// <returns></returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservering reservering = db.Reservering.Find(id);
            if (reservering == null)
            {
                return HttpNotFound();
            }
            return View(reservering);
        }

        // POST: Reservering/Delete/5
        /// <summary>
        /// Deletes the confirmed reservation.
        /// </summary>
        /// <param name="id">The id of the reservation.</param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservering reservering = db.Reservering.Find(id);
            db.Reservering.Remove(reservering);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Create a receipt for the reservation.
        /// </summary>
        /// <param name="id">The identifier of the reservation.</param>
        /// <returns></returns>
        public ActionResult Bon(int id)
        {
            var reservering = db.Reservering.Find(id);
            reservering.status = 0;
            reservering.betalingswijze = "pi";
            db.SaveChanges();
            List<Bestelling> bestelling = db.Bestelling.Where(res => res.reserveringId == id &&
            res.dateTimeBereidingConsumptie != null).ToList();
            return View(bestelling);
        }

        /// <summary>
        /// Creates a partial view for a customer.
        /// </summary>
        /// <param name="klantid">The id of the customer.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetCustomer(string klantid)
        {
            int nr = int.Parse(klantid);
            return PartialView("_Customer", db.Klant.First(k => k.klantId == nr));
        }

        /// <summary>
        /// Releases unmanaged resources and optionally releases managed resources.
        /// </summary>
        /// <param name="disposing">true to release both managed and unmanaged resources; false to release only unmanaged resources.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Reservering/Bon.cshtml
@model IEnumerable<ExcellentTaste.Models.Bestelling>


<h2>Bon</h2>
<table class="table">
    <tr>
        <th>
            Tijd: @DateTime.Now.ToString() Tafel: @Model.First().Reservering.tafel<br />
            ReserveringID: @Model.First().reserveringId
        </th>
    </tr>
</table>
@{ decimal totalPrice = 0; }
<table width="500">
    <tr>
        <th>Aantal</th>
        <th>Product</th>
        <th>Prijs</th>
    </tr>
@foreach (var item in Model)
{
    decimal price = item.aantal * item.prijs; // Calculate the price
    totalPrice += price;
    <tr>
        <td>@Html.DisplayFor(modelItem => item.aantal)</td>
        <td>@Html.DisplayFor(modelItem => item.ConsumptieItem.consumptieItemNaam)</td>
        <td>€ @Math.Round(price, 2)</td>
    </tr>
}

    @{ decimal vat = (totalPrice / 109) * 9;}
    <tr style="border-top-style:solid">
        <td colspan="2">Totaal: </td>
        <td>€ @Math.Round(totalPrice,2)</td>
    </tr>
    <tr>
        <td colspan="2">BTW 9% </td>
        <td> € @Math.Round(vat,2) </td>
    </tr>
</table>
    <br /><br />
<p>
    <a href="javascript:window.print()">Afdrukken</a>
</p>

Views/Reservering/Create.cshtml
@model ExcellentTaste.Models.VMReservering

@{
    ViewBag.Title = "Toevoegen";
}

<h2>Toevoegen</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reservering</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.klantId, "klantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @if (Model.klantId > 0)
                {
                    <div>@Html.DropDownList("klantId", new SelectList(Model.klantenLijst, "klantId", "klantNaam"), htmlAttributes: new { @class = "form-control", @disabled = "disabled" })</div>

                }
                else
                {
                    <div>
                        @Html.DropDownList("klantId", new SelectList(Model.klantenLijst, "klantId", "klantNaam"), htmlAttributes: new { @class = "form-control" }) 
                    </div >
                }
                @Html.ValidationMessageFor(model => model.klantId, "", new { @class = "text-danger" })
            </div>
            <div id="divDisplay" class="col-md-6">
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tijd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tijd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tijd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tafel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tafel, new { htmlAttributes = new { @class = "form-control", @type = "number", min = "1", Value = "1" } })
                @Html.ValidationMessageFor(model => model.tafel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aantalPersonen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aantalPersonen, new { htmlAttributes = new { @class = "form-control", @type = "number", min = "1", Value = "1" } })
                @Html.ValidationMessageFor(model => model.aantalPersonen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Toevoegen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#klantId").change(function () {
            var klantid = $("#klantId").val();
            $.ajax({
                data: "18",
                datatype: "text/plain",
                type: "POST",
                url: '/Reservering/GetCustomer?klantId=' + klantid,
                cache: false,
                success: function (data) {
                    $('#divDisplay').html(data);
                }
            });
        });
    </script>

}

Views/Reservering/Delete.cshtml
@model ExcellentTaste.Models.Reservering

@{
    ViewBag.Title = "Verwijder";
}

<h2>Verwijder</h2>

<h3>Weet u zeker dat u dit wilt verwijderen?</h3>
<div>
    <h4>Reservering</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.datum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tijd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tijd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tafel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tafel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aantalPersonen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aantalPersonen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datumToegevoegd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datumToegevoegd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bonDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bonDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.betalingswijze)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.betalingswijze)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Klant.klantNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Klant.klantNaam)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar overzicht", "Index")
        </div>
    }
</div>

Views/Reservering/Details.cshtml
@model ExcellentTaste.Models.Reservering

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reservering</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.datum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tijd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tijd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tafel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tafel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aantalPersonen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aantalPersonen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datumToegevoegd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datumToegevoegd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bonDatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bonDatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.betalingswijze)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.betalingswijze)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Klant.klantNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Klant.klantNaam)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Wijzig", "Edit", new { id = Model.reserveringId }) |
    @Html.ActionLink("Terug naar overzicht", "Index")
</p>

Views/Reservering/Edit.cshtml
@model ExcellentTaste.Models.Reservering

@{
    ViewBag.Title = "Edit";
}

<h2>Wijzig</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reservering</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.reserveringId)

        <div class="form-group">
            @Html.LabelFor(model => model.klantId, "klantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("klantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.klantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tijd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tijd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tijd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tafel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tafel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tafel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aantalPersonen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aantalPersonen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aantalPersonen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="hidden">
            <div class="form-group">
                @Html.LabelFor(model => model.datumToegevoegd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.datumToegevoegd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.datumToegevoegd, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.bonDatum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.bonDatum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.bonDatum, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.betalingswijze, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.betalingswijze, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.betalingswijze, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Reservering/Index.cshtml
@model IEnumerable<ExcellentTaste.Models.Reservering>

@{
    ViewBag.Title = "Index";
}

<h2>Overzicht reserveringen</h2>

<p>
    @Html.ActionLink("Toevoegen", "Create", "Reservering", null, new { @class = "btn btn-primary btn-large" })
</p>
<div>
    <h4>Legenda</h4>
    <table id="legenda">
        <tr>
            <td><span class="glyphicon glyphicon-ok">Afgerond</span></td>
            <td><span class="glyphicon glyphicon-time">Afwachting</span></td>
            <td><span class="glyphicon glyphicon-record">Lopend</span></td>
        </tr>

    </table>


</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tijd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tafel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.aantalPersonen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Klant.klantNaam)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @if (item.status == 0)
            {
                <span class="glyphicon glyphicon-ok">&nbsp;</span>
            }
            else if (item.status == 1 && item.datum > DateTime.Now)
            {
                <span class="glyphicon glyphicon-time">&nbsp;</span>
            }
            else
            {
                <span class="glyphicon glyphicon-record">&nbsp;</span>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tijd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tafel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.aantalPersonen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Klant.klantNaam)
        </td>
        <td>
            @Html.ActionLink("Wijzig", "Edit", new { id = item.reserveringId }) |
            @Html.ActionLink("Details", "Details", new { id = item.reserveringId })
            @if (item.status == 1 && item.Bestelling.Count == 0)
            {
                <span>
                    | @Html.ActionLink("Verwijder", "Delete", new { id = item.reserveringId })
                </span>
            }
        </td>
    </tr>
    }

</table>

Views/Reservering/Today.cshtml
@model IEnumerable<ExcellentTaste.Models.GET_TODAYS_RESERVATIONS_Result>

@{
    ViewBag.Title = "Index";
}

<h2>Reserveringen van vandaag</h2>

<p>
    @Html.ActionLink("Toevoegen", "Create", "Reservering", null, new { @class = "btn btn-primary btn-large" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.tijd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.klantNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tafel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.aantalPersonen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datumToegevoegd)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tijd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.klantNaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tafel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.aantalPersonen)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.datumToegevoegd)
            </td>
            @*Disable the dropdown if the order is already attached 
                to a reservation
            *@
            <td>
                @if (item.BonBestellingen > 0 && item.status == 1)
                {
                    @Html.ActionLink("Bon", "Bon", new { id = item.reserveringId })
                }
            </td>
            <td>
                @if (item.status == 1 && item.tijd < DateTime.Now.TimeOfDay)
                {
                    @Html.ActionLink("Bestelling opnemen", "Create", "Bestelling" , new { reserveringid = item.reserveringId },null)
                }
            </td>


        </tr>
    }

</table>

Views/Reservering/_Customer.cshtml
@model ExcellentTaste.Models.Klant

@if (Model.Actief)
{
    <div>
        Telefoon: @Html.DisplayFor(model => model.telefoon)
    </div>
}
else
{
    <div style="background-color:lightcoral">
        <p>Klant is bij vorige reservering niet gekomen!</p>
        Telefoon: @Html.DisplayFor(model => model.telefoon)
    </div>
}