Models/Klant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentTaste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klant()
        {
            this.Reservering = new HashSet<Reservering>();
        }
    
        public int klantId { get; set; }
        public string klantNaam { get; set; }
        public string telefoon { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservering> Reservering { get; set; }
    }
}

Controllers/KlantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExcellentTaste.Models;

namespace ExcellentTaste.Controllers
{
    public class KlantController : Controller
    {
        private Entities db = new Entities();

        // GET: Klant
        public ActionResult Index(string filter = "")
        {
            if (filter == "")
            {
                return View(db.Klant.ToList());
            }
            else
            {
                return View(db.Klant.Where(k => k.klantNaam.Contains(filter)).ToList());
            }
        }

        // GET: Klant/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klant klant = db.Klant.Find(id);
            if (klant == null)
            {
                return HttpNotFound();
            }
            return View(klant);
        }

        // GET: Klant/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Klant/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "klantId,klantNaam,telefoon,status")] Klant klant)
        {
            if (ModelState.IsValid)
            {
                db.Klant.Add(klant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(klant);
        }

        // GET: Klant/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klant klant = db.Klant.Find(id);
            if (klant == null)
            {
                return HttpNotFound();
            }
            return View(klant);
        }

        // POST: Klant/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "klantId,klantNaam,telefoon,status")] Klant klant)
        {
            // New customers always get a status of 1 = reliable
            klant.status = 1;
            if (ModelState.IsValid)
            {
                db.Entry(klant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(klant);
        }

        // GET: Klant/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klant klant = db.Klant.Find(id);
            if (klant == null)
            {
                return HttpNotFound();
            }
            return View(klant);
        }

        // POST: Klant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Klant klant = db.Klant.Find(id);
            db.Klant.Remove(klant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Klant/Create.cshtml
@model ExcellentTaste.Models.Klant

@{
    ViewBag.Title = "Toevoegen";
}

<h2>Toevoegen</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Klant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.klantNaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.klantNaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.klantNaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefoon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefoon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefoon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Toevoegen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Klant/Delete.cshtml
@model ExcellentTaste.Models.Klant

@{
    ViewBag.Title = "Verwijder";
}

<h2>Verwijder</h2>

<h3>Weet u zeker dat u dit wilt verwijderen?</h3>
<div>
    <h4>Klant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.klantNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.klantNaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefoon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefoon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar overzicht", "Index")
        </div>
    }
</div>

Views/Klant/Details.cshtml
@model ExcellentTaste.Models.Klant

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Klant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.klantNaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.klantNaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefoon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefoon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Wijzig", "Edit", new { id = Model.klantId }) |
    @Html.ActionLink("Terug naar overzicht", "Index")
</p>

Views/Klant/Edit.cshtml
@model ExcellentTaste.Models.Klant

@{
    ViewBag.Title = "Edit";
}

<h2>Wijzig</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Klant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.klantId)

        <div class="form-group">
            @Html.LabelFor(model => model.klantNaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.klantNaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.klantNaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefoon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefoon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefoon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Klant/Index.cshtml
@model IEnumerable<ExcellentTaste.Models.Klant>

@{
    ViewBag.Title = "Index";
}

<h2>Overzicht klanten</h2>
<div>
    <form>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search" name="filter">
        </div>
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
        </button>
        <br />
    </form>
</div>

<hr/>

<p>
    @Html.ActionLink("Toevoegen", "Create", "Klant", null, new { @class = "btn btn-primary btn-large" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.klantNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefoon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Actief)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.klantNaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefoon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actief)
            </td>
            <td>
                @Html.ActionLink("Wijzig", "Edit", new { id = item.klantId }) |
                @Html.ActionLink("Details", "Details", new { id = item.klantId }) |
                @Html.ActionLink("Verwijder", "Delete", new { id = item.klantId })
            </td>
            <td>
                @if (item.Reservering.Count > 0)
                {
                    @Html.ActionLink("Reserveringen", "Index", "Reservering", new { klantId = item.klantId }, null);
                }
                @Html.ActionLink("Reserveer", "Create", "Reservering", new { klantId = item.klantId }, null)
            </td>
        </tr>
    }

</table>