Models/Bestelling.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentTaste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {
        public int bestellingId { get; set; }
        public int reserveringId { get; set; }
        public string consumptieItemCode { get; set; }
        public int aantal { get; set; }
        public Nullable<System.DateTime> dateTimeBereidingConsumptie { get; set; }
        public decimal prijs { get; set; }
        public Nullable<decimal> totaal { get; set; }
    
        public virtual ConsumptieItem ConsumptieItem { get; set; }
        public virtual Reservering Reservering { get; set; }
    }
}

Controllers/BestellingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExcellentTaste.Models;

namespace ExcellentTaste.Controllers
{
    [Authorize]
    public class BestellingController : Controller
    {
        private Entities db = new Entities();

        // GET: Bestelling
        public ActionResult Index()
        {
            var bestelling = db.Bestelling.Include(b => b.ConsumptieItem).Include(b => b.Reservering);
            return View(bestelling.ToList());
        }

        public ActionResult Bar()
        {
            var overzichtDranken =
                db.Bestelling.Where(b => b.ConsumptieItem.ConsumptieGroep.Consumptie.consumptieCode.ToLower() == "drk"
                && b.Reservering.datum == DateTime.Today && b.dateTimeBereidingConsumptie == null).OrderBy(b => b.Reservering.tafel);
            return View(overzichtDranken);
        }

        public ActionResult Keuken()
        {
            var overzichtDranken =
                db.Bestelling.Where(b => b.ConsumptieItem.ConsumptieGroep.Consumptie.consumptieCode.ToLower() != "drk"
                && b.Reservering.datum == DateTime.Today && b.dateTimeBereidingConsumptie == null).OrderBy(b => b.Reservering.tafel);
            return View(overzichtDranken);
        }

        public ActionResult ToReceipt(int id, char from)
        {
            Bestelling bestelling = db.Bestelling.First(b => b.bestellingId == id);
            bestelling.dateTimeBereidingConsumptie = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Entry(bestelling).State = EntityState.Modified;
                db.SaveChanges();
                if (from == 'B')
                    return RedirectToAction("Bar");
                else
                    return RedirectToAction("Keuken");
            }
            ViewBag.consumptieItemCode = new SelectList(db.ConsumptieItem, "consumptieItemCode", "consumptieGroepCode", bestelling.consumptieItemCode);
            ViewBag.reserveringId = new SelectList(db.Reservering, "reserveringId", "betalingswijze", bestelling.reserveringId);
            return View(bestelling);
        }

        // GET: Bestelling/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bestelling bestelling = db.Bestelling.Find(id);
            if (bestelling == null)
            {
                return HttpNotFound();
            }
            return View(bestelling);
        }

        // GET: Bestelling/Create
        public ActionResult Create(int reserveringid = 0)
        {

            //Create the select list item you want to add
            SelectListItem selListItem = new SelectListItem() { Value = "null", Text = "Select One" };

            //Create a list of select list items - this will be returned as your select list
            List<SelectListItem> newList = new List<SelectListItem>();
            newList.Add(selListItem);
            foreach (var item in db.ConsumptieItem.OrderBy(ci => ci.consumptieItemNaam))
            {
                newList.Add(new SelectListItem() { Value = item.consumptieItemCode, Text = item.consumptieItemNaam });
            }
            //ViewBag.consumptieItemCode = new SelectList(db.ConsumptieItem.OrderBy(ci => ci.consumptieItemNaam), "consumptieItemCode", "consumptieItemNaam");
            ViewBag.consumptieItemCode = newList;
            DateTime today = DateTime.Today;
            TimeSpan now = DateTime.Now.TimeOfDay;
            List<SelectListItem> reserveringen = new List<SelectListItem>();
            foreach (var item in db.Reservering.Where(r => r.datum == today && r.tijd <= now && r.status == 1))
            {
                var selectListItem = new SelectListItem();
                selectListItem.Value = item.reserveringId.ToString();
                selectListItem.Text = item.tafel.ToString();
                selectListItem.Selected = item.reserveringId == reserveringid;
                reserveringen.Add(selectListItem);
            }
            ViewBag.reserveringId = reserveringen;

            // Status 1 is een bestelling die geplaatst wordt vanuit een reservering
            // Status 0 is een bestelling die wordt geplaatst vanuit het hoofdmenu
            ViewBag.status = reserveringid == 0 ? 0 : 1;
            return View();
        }

        // POST: Bestelling/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "bestellingId,reserveringId,consumptieItemCode,aantal")] Bestelling bestelling)
        {
           
            if (bestelling.consumptieItemCode == "null")
            {
                //ViewBag.error = "Kies eerst een consumptie of gerecht";
                //Create the select list item you want to add
                SelectListItem selListItem = new SelectListItem() { Value = "null", Text = "Select One" };

                //Create a list of select list items - this will be returned as your select list
                List<SelectListItem> newList = new List<SelectListItem>();
                newList.Add(selListItem);
                foreach (var item in db.ConsumptieItem.OrderBy(ci => ci.consumptieItemNaam))
                {
                    newList.Add(new SelectListItem() { Value = item.consumptieItemCode, Text = item.consumptieItemNaam });
                }
                //ViewBag.consumptieItemCode = new SelectList(db.ConsumptieItem.OrderBy(ci => ci.consumptieItemNaam), "consumptieItemCode", "consumptieItemNaam");
                ViewBag.consumptieItemCode = newList;
                DateTime today = DateTime.Today;
                TimeSpan now = DateTime.Now.TimeOfDay;
                SelectList list = new SelectList(db.Reservering.Where(r => r.datum == today && r.tijd <= now && r.status == 1), "reserveringId", "tafel");

                ViewBag.reserveringId = list;
                TempData["error"] = "Kies eerst een consumptie of gerecht";
                return RedirectToAction("Create", new { reserveringid = bestelling.reserveringId });
            }
            if (ModelState.IsValid)
            {
                // Get the current price for the consumption item
                bestelling.prijs = db.ConsumptieItem.FirstOrDefault(ci => ci.consumptieItemCode == bestelling.consumptieItemCode).prijs;
                db.Bestelling.Add(bestelling);
                db.SaveChanges();
                return RedirectToAction("Create",new { reserveringid = bestelling.reserveringId});
            }

            ViewBag.consumptieItemCode = new SelectList(db.ConsumptieItem.OrderBy(ci => ci.consumptieItemNaam), "consumptieItemCode", "consumptieGroepCode", bestelling.consumptieItemCode);
            ViewBag.reserveringId = new SelectList(db.Reservering, "reserveringId", "betalingswijze", bestelling.reserveringId);
            return View("Create");
        }

        // GET: Bestelling/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bestelling bestelling = db.Bestelling.Find(id);
            if (bestelling == null)
            {
                return HttpNotFound();
            }
            ViewBag.consumptieItemCode = new SelectList(db.ConsumptieItem.OrderBy(ci => ci.consumptieItemNaam), "consumptieItemCode", "consumptieGroepCode", bestelling.consumptieItemCode);
            ViewBag.reserveringId = new SelectList(db.Reservering, "reserveringId", "betalingswijze", bestelling.reserveringId);
            return View(bestelling);
        }

        // POST: Bestelling/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "bestellingId,reserveringId,consumptieItemCode,aantal,dateTimeBereidingConsumptie")] Bestelling bestelling)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bestelling).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.consumptieItemCode = new SelectList(db.ConsumptieItem.OrderBy(ci => ci.consumptieItemNaam), "consumptieItemCode", "consumptieGroepCode", bestelling.consumptieItemCode);
            ViewBag.reserveringId = new SelectList(db.Reservering, "reserveringId", "betalingswijze", bestelling.reserveringId);
            return View(bestelling);
        }

        // GET: Bestelling/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bestelling bestelling = db.Bestelling.Find(id);
            if (bestelling == null)
            {
                return HttpNotFound();
            }
            return View(bestelling);
        }

        // POST: Bestelling/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bestelling bestelling = db.Bestelling.Find(id);
            db.Bestelling.Remove(bestelling);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

Views/Bestelling/Bar.cshtml
@model IEnumerable<ExcellentTaste.Models.Bestelling>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Reservering.tafel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieGroepCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieItemNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.aantal)
        </th>

        <th>Uitlevering</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Reservering.tafel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConsumptieItem.consumptieGroepCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConsumptieItem.consumptieItemNaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.aantal)
            </td>
            <td>
                @if (item.dateTimeBereidingConsumptie != null)
                {
                <span>@item.dateTimeBereidingConsumptie.ToString()</span>
                    //Html.ActionLink("Naar bon", "ToReceipt", new { id = item.bestellingId });
                }
                else
                {
                    <a href="/Bestelling/ToReceipt?id=@item.bestellingId&from=B">Naar bon</a>

                    //Html.DisplayFor(modelIem => item.dateTimeBereidingConsumptie);
                }
            </td>
        </tr>
    }

</table>

Views/Bestelling/Create.cshtml
@model ExcellentTaste.Models.Bestelling

@{
    ViewBag.Title = "Toevoegen";
}

<h2>Toevoegen</h2>
@if (TempData["error"] != null)
{
    <div class="label-warning">@TempData["error"]</div>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bestelling</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.reserveringId, "Tafel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (ViewBag.status == 1)
                {
                    <span>@Html.DropDownList("reserveringId", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })</span>
                }
                else
                {
                    <span>@Html.DropDownList("reserveringId", null, htmlAttributes: new { @class = "form-control" })</span>
                }
                @Html.ValidationMessageFor(model => model.reserveringId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.consumptieItemCode, "Consumptie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("consumptieItemCode", null, htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.consumptieItemCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aantal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aantal, new { htmlAttributes = new { @class = "form-control", @type = "number", min = "1", Value = "1" } })
                @Html.ValidationMessageFor(model => model.aantal, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Toevoegen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Terug naar overzicht", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

Views/Bestelling/Delete.cshtml
@model ExcellentTaste.Models.Bestelling

@{
    ViewBag.Title = "Verwijder";
}

<h2>Verwijder</h2>

<h3>Weet u zeker dat u dit wilt verwijderen?</h3>
<div>
    <h4>Bestelling</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.aantal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aantal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateTimeBereidingConsumptie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateTimeBereidingConsumptie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieGroepCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumptieItem.consumptieGroepCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reservering.betalingswijze)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reservering.betalingswijze)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar overzicht", "Index")
        </div>
    }
</div>

Views/Bestelling/Details.cshtml
@model ExcellentTaste.Models.Bestelling

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bestelling</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.aantal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aantal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateTimeBereidingConsumptie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateTimeBereidingConsumptie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieGroepCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsumptieItem.consumptieGroepCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reservering.betalingswijze)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reservering.betalingswijze)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Wijzig", "Edit", new { id = Model.bestellingId }) |
    @Html.ActionLink("Terug naar overzicht", "Index")
</p>

Views/Bestelling/Edit.cshtml
@model ExcellentTaste.Models.Bestelling

@{
    ViewBag.Title = "Edit";
}

<h2>Wijzig</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bestelling</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.bestellingId)

        <div class="form-group">
            @Html.LabelFor(model => model.reserveringId, "reserveringId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("reserveringId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.reserveringId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.consumptieItemCode, "consumptieItemCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("consumptieItemCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.consumptieItemCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.aantal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aantal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aantal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateTimeBereidingConsumptie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateTimeBereidingConsumptie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateTimeBereidingConsumptie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Bestelling/Index.cshtml
@model IEnumerable<ExcellentTaste.Models.Bestelling>

@{
    ViewBag.Title = "Index";
}

<h2>Overzicht bestellingen</h2>

<p>
    @Html.ActionLink("Toevoegen", "Create", "Bestelling", null, new { @class = "btn btn-primary btn-large" })
</p>
<table class="table">
    <tr>
        <th>
            Tafel
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieGroepCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieItemNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.aantal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Reservering.tafel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConsumptieItem.consumptieGroepCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConsumptieItem.consumptieItemNaam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.aantal)
        </td>
        <td>
            @Html.ActionLink("Wijzig", "Edit", new { id = item.bestellingId }) |
            @Html.ActionLink("Details", "Details", new { id = item.bestellingId }) |
            @Html.ActionLink("Verwijder", "Delete", new { id = item.bestellingId })
        </td>
    </tr>
}

</table>

Views/Bestelling/Keuken.cshtml
@model IEnumerable<ExcellentTaste.Models.Bestelling>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Reservering.tafel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieGroepCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConsumptieItem.consumptieItemNaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.aantal)
        </th>
        <th>Uitlevering</th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Reservering.tafel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConsumptieItem.consumptieGroepCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConsumptieItem.consumptieItemNaam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.aantal)
        </td>
        <td>
            @if (item.dateTimeBereidingConsumptie != null)
            {
                <span>@item.dateTimeBereidingConsumptie.ToString()</span>
                //Html.ActionLink("Naar bon", "ToReceipt", new { id = item.bestellingId });
            }
            else
            {
                <a href="/Bestelling/ToReceipt?id=@item.bestellingId&from=K">Naar bon</a>

                //Html.DisplayFor(modelIem => item.dateTimeBereidingConsumptie);
            }
        </td>
    </tr>
    }

</table>